### ISSUE TITLE
由于自定义积木输入不当造成编辑问题

### ISSUE THREAD

**Issue by SimonShiki** [Clipteam/clipcc-gui#119]
### 描述一下bug
由于自定义积木输入不当造成生成的积木显示异常 并造成原有积木无法编辑
## 请叙述bug触发步骤
见视频
## 预期的行为
与原版保持一致
## 截图或视频

https://user-images.githubusercontent.com/59327348/160840397-ee954f29-bda5-4359-ba99-7901983fa628.mp4

## ClipCC版本
仅测试金丝雀版，但稳定版大概率可复现
## 附加内容
报错：
```
TypeError: undefined is not an object (evaluating 'a.paddingStart=0')
  at ? (/editor/canary/chunks/ccblocks.js:3551:241)
  at ? (/editor/canary/chunks/ccblocks.js:3546:281)
  at ? (/editor/canary/chunks/ccblocks.js:3538:475)
  at ? (/editor/canary/chunks/ccblocks.js:3513:307)
  at ? (/editor/canary/chunks/ccblocks.js:1937:177)
  at setBlocks(/editor/canary/lib.min.js:297847:43)
  at wrapper(/editor/canary/lib.min.js:178336:20)
  at commitAttachRef(/editor/canary/lib.min.js:228035:10)
  at commitLayoutEffects(/editor/canary/lib.min.js:230591:24)
  at callCallback(/editor/canary/lib.min.js:211110:19)
  at sentryWrapped(../src/helpers.ts:98:17)
  at dispatchEvent([native code])
  at invokeGuardedCallbackDev(/editor/canary/lib.min.js:211159:29)
  at invokeGuardedCallback(/editor/canary/lib.min.js:211221:36)
  at commitRootImpl(/editor/canary/lib.min.js:230311:30)
  at commitRootImpl([native code])
  at unstable_runWithPriority(/editor/canary/lib.min.js:268803:24)
  at commitRoot(/editor/canary/lib.min.js:230150:20)
  at performSyncWorkOnRoot(/editor/canary/lib.min.js:229489:13)
  at performSyncWorkOnRoot([native code])
  at ? (/editor/canary/lib.min.js:218492:34)
  at unstable_runWithPriority(/editor/canary/lib.min.js:268803:24)
  at flushSyncCallbackQueueImpl(/editor/canary/lib.min.js:218487:26)
  at flushSyncCallbackQueue(/editor/canary/lib.min.js:218474:29)
  at batchedUpdates$1(/editor/canary/lib.min.js:229547:29)
  at notify(/editor/canary/lib.min.js:243133:12)
  at notifyNestedSubs(/editor/canary/lib.min.js:243203:21)
  at handleChangeWrapper(/editor/canary/lib.min.js:243208:33)
  at dispatch(/editor/canary/lib.min.js:267501:15)
  at ? (/editor/canary/chunks/ccblocks.js:4035:48)
  at callback(/editor/canary/chunks/ccblocks.js:4036:158)
  at ? (/editor/canary/chunks/ccblocks.js:3227:302)
  at ? (/editor/canary/chunks/ccblocks.js:3229:493)
  at ? (/editor/canary/chunks/ccblocks.js:3360:188)
  at ? (/editor/canary/chunks/ccblocks.js:3418:298)
  at ? (/editor/canary/chunks/ccblocks.js:3384:262)
```

**Comment by SimonShiki** [comment]
已修复
