### ISSUE TITLE
当积木包含不返回任何值的返回值积木时会被跳过

### ISSUE THREAD

**Issue by SimonShiki** [Clipteam/clipcc-gui#124]
### 描述一下bug
在项目运行时偶发报错导致运行异常
## 请叙述bug触发步骤
1.运行一个逻辑较为复杂的项目（Eg: PaperMinecraft, ALLTALE）
## 预期的行为
与原版行为一致
## 截图或视频
![image](https://user-images.githubusercontent.com/59327348/162971806-9a031c52-4781-4b7b-9525-2785ddcc57a1.png)

## ClipCC版本
3.1以之后所有版本均有此问题
## 附加内容
报错信息
```
Uncaught TypeError: Cannot read properties of null (reading 'isExcuted')
    at j.stepThread (348.654e89cbe8cab020.js:1:5190814)
    at j.stepThreads (348.654e89cbe8cab020.js:1:5189655)
    at L._step (348.654e89cbe8cab020.js:1:2228165)
    at 348.654e89cbe8cab020.js:1:2233354
```
该bug主要表现在作品突然停止运行，在一段时间后恢复正常

**Comment by SimonShiki** [comment]
该报错来源于vm/src/engine/sequencer.js:242
![image](https://user-images.githubusercontent.com/59327348/162972069-dca9a8d2-8d9f-4cad-82d6-47df2167b7c0.png)

**Comment by SimonShiki** [comment]
该问题疑似导致部分程序无法正常运行，故调整至p3

**Comment by SimonShiki** [comment]
已revert问题commit

**Comment by SimonShiki** [comment]
已被修复
