### ISSUE TITLE
（续）声音区新增声音后删所有声音会崩

### ISSUE THREAD

**Issue by NanHaiJuRuo** [Clipteam/clipcc-gui#161]
### 描述一下bug
虽然已修复删除自带声音导致的假报错，但是新增一个声音再删除还是会报错。
## 请叙述bug触发步骤
打开编辑器，进入声音区，删除声音。此时并没有出现报错，然而在下方添加随机声音后再次删除，报错出现。
## 预期的行为
正常删除但不会报错
## 截图或视频
视频见QQ群文件：  
codingclip 声音区新增声音后删所有声音会崩.mp4
截图：
![](https://user-images.githubusercontent.com/109646559/181183253-c3e78d96-77c7-469e-bbc6-f74edfb29327.png)
## ClipCC版本
c3.1.3
## 附加内容
续上次被关的帖子

**Comment by SimonShiki** [comment]
仍然无法触发

**Comment by sparrowhe** [comment]
canary 可以复现

```
gui Unhandled Error: TypeError: Cannot read properties of undefined (reading 'soundId')    at VirtualMachine.getSoundBuffer (https://codingclip.com/editor/canary/lib.min.js:162572:61)    at Function.mapStateToProps [as mapToProps] (https://codingclip.com/editor/canary/lib.min.js:298966:43)    at mapToPropsProxy (https://codingclip.com/editor/canary/lib.min.js:241830:46)    at handleNewState (https://codingclip.com/editor/canary/lib.min.js:241699:26)    at handleSubsequentCalls (https://codingclip.com/editor/canary/lib.min.js:241713:30)    at pureFinalPropsSelector (https://codingclip.com/editor/canary/lib.min.js:241718:32)    at Object.checkForUpdates (https://codingclip.com/editor/canary/lib.min.js:241092:23)    at Object.handleChangeWrapper [as callback] (https://codingclip.com/editor/canary/lib.min.js:242395:20)    at https://codingclip.com/editor/canary/lib.min.js:242324:20    at batchedUpdates$1 (https://codingclip.com/editor/canary/lib.min.js:228727:12)    at Object.notify (https://codingclip.com/editor/canary/lib.min.js:242320:7)    at Object.notifyNestedSubs (https://codingclip.com/editor/canary/lib.min.js:242390:15)    at Object.checkForUpdates [as onStateChange] (https://codingclip.com/editor/canary/lib.min.js:241105:9)    at Object.handleChangeWrapper [as callback] (https://codingclip.com/editor/canary/lib.min.js:242395:20)    at https://codingclip.com/editor/canary/lib.min.js:242324:20    at batchedUpdates$1 (https://codingclip.com/editor/canary/lib.min.js:228727:12)    at Object.notify (https://codingclip.com/editor/canary/lib.min.js:242320:7)    at Object.notifyNestedSubs (https://codingclip.com/editor/canary/lib.min.js:242390:15)    at Object.checkForUpdates [as onStateChange] (https://codingclip.com/editor/canary/lib.min.js:241105:9)    at Object.handleChangeWrapper [as callback] (https://codingclip.com/editor/canary/lib.min.js:242395:20)    at https://codingclip.com/editor/canary/lib.min.js:242324:20    at batchedUpdates$1 (https://codingclip.com/editor/canary/lib.min.js:228727:12)    at Object.notify (https://codingclip.com/editor/canary/lib.min.js:242320:7)    at Object.notifyNestedSubs (https://codingclip.com/editor/canary/lib.min.js:242390:15)    at Object.checkForUpdates [as onStateChange] (https://codingclip.com/editor/canary/lib.min.js:241105:9)    at Object.handleChangeWrapper [as callback] (https://codingclip.com/editor/canary/lib.min.js:242395:20)    at https://codingclip.com/editor/canary/lib.min.js:242324:20    at batchedUpdates$1 (https://codingclip.com/editor/canary/lib.min.js:228727:12)    at Object.notify (https://codingclip.com/editor/canary/lib.min.js:242320:7)    at Object.notifyNestedSubs (https://codingclip.com/editor/canary/lib.min.js:242390:15)    at Object.checkForUpdates [as onStateChange] (https://codingclip.com/editor/canary/lib.min.js:241105:9)    at Object.handleChangeWrapper [as callback] (https://codingclip.com/editor/canary/lib.min.js:242395:20)    at https://codingclip.com/editor/canary/lib.min.js:242324:20    at batchedUpdates$1 (https://codingclip.com/editor/canary/lib.min.js:228727:12)    at Object.notify (https://codingclip.com/editor/canary/lib.min.js:242320:7)    at Object.notifyNestedSubs (https://codingclip.com/editor/canary/lib.min.js:242390:15)    at Object.checkForUpdates [as onStateChange] (https://codingclip.com/editor/canary/lib.min.js:241105:9)    at Object.handleChangeWrapper [as callback] (https://codingclip.com/editor/canary/lib.min.js:242395:20)    at https://codingclip.com/editor/canary/lib.min.js:242324:20    at batchedUpdates$1 (https://codingclip.com/editor/canary/lib.min.js:228727:12)    at Object.notify (https://codingclip.com/editor/canary/lib.min.js:242320:7)    at Object.notifyNestedSubs (https://codingclip.com/editor/canary/lib.min.js:242390:15)    at Object.checkForUpdates [as onStateChange] (https://codingclip.com/editor/canary/lib.min.js:241105:9)    at Object.handleChangeWrapper [as callback] (https://codingclip.com/editor/canary/lib.min.js:242395:20)    at https://codingclip.com/editor/canary/lib.min.js:242324:20    at batchedUpdates$1 (https://codingclip.com/editor/canary/lib.min.js:228727:12)    at Object.notify (https://codingclip.com/editor/canary/lib.min.js:242320:7)    at Object.notifyNestedSubs (https://codingclip.com/editor/canary/lib.min.js:242390:15)    at Object.checkForUpdates [as onStateChange] (https://codingclip.com/editor/canary/lib.min.js:241105:9)    at Object.handleChangeWrapper [as callback] (https://codingclip.com/editor/canary/lib.min.js:242395:20)Component stack:     at ConnectFunction (https://codingclip.com/editor/canary/lib.min.js:241246:75)    at div    at Box (https://codingclip.com/editor/canary/lib.min.js:278433:5)    at div    at Box (https://codingclip.com/editor/canary/lib.min.js:278433:5)    at AssetPanel (https://codingclip.com/editor/canary/lib.min.js:277588:10)    at SoundTab (https://codingclip.com/editor/canary/lib.min.js:299276:5)    at ConnectFunction (https://codingclip.com/editor/canary/lib.min.js:241246:75)    at injectIntl(Connect(SoundTab))    at ErrorBoundary (https://codingclip.com/editor/canary/lib.min.js:294601:5)    at ConnectFunction (https://codingclip.com/editor/canary/lib.min.js:241246:75)    at ErrorBoundaryWrapper    at div    at TabPanel (https://codingclip.com/editor/canary/lib.min.js:245646:24)    at div    at UncontrolledTabs (https://codingclip.com/editor/canary/lib.min.js:245895:70)    at Tabs (https://codingclip.com/editor/canary/lib.min.js:245739:24)    at div    at Box (https://codingclip.com/editor/canary/lib.min.js:278433:5)    at div    at Box (https://codingclip.com/editor/canary/lib.min.js:278433:5)    at div    at Box (https://codingclip.com/editor/canary/lib.min.js:278433:5)    at div    at Box (https://codingclip.com/editor/canary/lib.min.js:278433:5)    at MediaQuery (https://codingclip.com/editor/canary/lib.min.js:243795:33)    at GUIComponent    at ConnectFunction (https://codingclip.com/editor/canary/lib.min.js:241246:75)    at injectIntl(Connect(GUIComponent))    at GUI (https://codingclip.com/editor/canary/lib.min.js:295289:5)    at ConnectFunction (https://codingclip.com/editor/canary/lib.min.js:241246:75)    at injectIntl(Connect(GUI))    at CloudManager (https://codingclip.com/editor/canary/lib.min.js:303908:7)    at ConnectFunction (https://codingclip.com/editor/canary/lib.min.js:241246:75)    at SBFileUploaderComponent (https://codingclip.com/editor/canary/lib.min.js:309754:7)    at ConnectFunction (https://codingclip.com/editor/canary/lib.min.js:241246:75)    at injectIntl(Connect(SBFileUploaderComponent))    at VMManager (https://codingclip.com/editor/canary/lib.min.js:311562:7)    at ConnectFunction (https://codingclip.com/editor/canary/lib.min.js:241246:75)    at VMListener (https://codingclip.com/editor/canary/lib.min.js:311314:7)    at ConnectFunction (https://codingclip.com/editor/canary/lib.min.js:241246:75)    at ProjectSaverComponent (https://codingclip.com/editor/canary/lib.min.js:309033:7)    at ConnectFunction (https://codingclip.com/editor/canary/lib.min.js:241246:75)    at TitledComponent (https://codingclip.com/editor/canary/lib.min.js:310658:3)    at ConnectFunction (https://codingclip.com/editor/canary/lib.min.js:241246:75)    at injectIntl(Connect(TitledComponent))    at ProjectFetcherComponent (https://codingclip.com/editor/canary/lib.min.js:308849:7)    at ConnectFunction (https://codingclip.com/editor/canary/lib.min.js:241246:75)    at injectIntl(Connect(ProjectFetcherComponent))    at QueryParserComponent (https://codingclip.com/editor/canary/lib.min.js:309529:7)    at ConnectFunction (https://codingclip.com/editor/canary/lib.min.js:241246:75)    at FontLoaderComponent (https://codingclip.com/editor/canary/lib.min.js:306108:3)    at ConnectFunction (https://codingclip.com/editor/canary/lib.min.js:241246:75)    at ErrorBoundary (https://codingclip.com/editor/canary/lib.min.js:294601:5)    at ConnectFunction (https://codingclip.com/editor/canary/lib.min.js:241246:75)    at ErrorBoundaryWrapper    at IntlProvider (https://codingclip.com/editor/canary/lib.min.js:236950:9)    at ConnectFunction (https://codingclip.com/editor/canary/lib.min.js:241246:75)    at LocalizationWrapper (https://codingclip.com/editor/canary/lib.min.js:308173:3)    at ConnectFunction (https://codingclip.com/editor/canary/lib.min.js:241246:75)    at HashParserComponent (https://codingclip.com/editor/canary/lib.min.js:306341:7)    at ConnectFunction (https://codingclip.com/editor/canary/lib.min.js:241246:75)    at IntlProvider (https://codingclip.com/editor/canary/lib.min.js:236950:9)    at ConnectFunction (https://codingclip.com/editor/canary/lib.min.js:241246:75)    at Provider (https://codingclip.com/editor/canary/lib.min.js:240957:20)    at AppStateWrapper (https://codingclip.com/editor/canary/lib.min.js:301993:7) 
    at ErrorBoundary (https://codingclip.com/editor/canary/lib.min.js:294601:5)
    at ConnectFunction (https://codingclip.com/editor/canary/lib.min.js:241246:75)
    at ErrorBoundaryWrapper
    at div
    at TabPanel (https://codingclip.com/editor/canary/lib.min.js:245646:24)
    at div
    at UncontrolledTabs (https://codingclip.com/editor/canary/lib.min.js:245895:70)
    at Tabs (https://codingclip.com/editor/canary/lib.min.js:245739:24)
    at div
    at Box (https://codingclip.com/editor/canary/lib.min.js:278433:5)
    at div
    at Box (https://codingclip.com/editor/canary/lib.min.js:278433:5)
    at div
    at Box (https://codingclip.com/editor/canary/lib.min.js:278433:5)
    at div
    at Box (https://codingclip.com/editor/canary/lib.min.js:278433:5)
    at MediaQuery (https://codingclip.com/editor/canary/lib.min.js:243795:33)
    at GUIComponent
    at ConnectFunction (https://codingclip.com/editor/canary/lib.min.js:241246:75)
    at injectIntl(Connect(GUIComponent))
    at GUI (https://codingclip.com/editor/canary/lib.min.js:295289:5)
    at ConnectFunction (https://codingclip.com/editor/canary/lib.min.js:241246:75)
    at injectIntl(Connect(GUI))
    at CloudManager (https://codingclip.com/editor/canary/lib.min.js:303908:7)
    at ConnectFunction (https://codingclip.com/editor/canary/lib.min.js:241246:75)
    at SBFileUploaderComponent (https://codingclip.com/editor/canary/lib.min.js:309754:7)
    at ConnectFunction (https://codingclip.com/editor/canary/lib.min.js:241246:75)
    at injectIntl(Connect(SBFileUploaderComponent))
    at VMManager (https://codingclip.com/editor/canary/lib.min.js:311562:7)
    at ConnectFunction (https://codingclip.com/editor/canary/lib.min.js:241246:75)
    at VMListener (https://codingclip.com/editor/canary/lib.min.js:311314:7)
    at ConnectFunction (https://codingclip.com/editor/canary/lib.min.js:241246:75)
    at ProjectSaverComponent (https://codingclip.com/editor/canary/lib.min.js:309033:7)
    at ConnectFunction (https://codingclip.com/editor/canary/lib.min.js:241246:75)
    at TitledComponent (https://codingclip.com/editor/canary/lib.min.js:310658:3)
    at ConnectFunction (https://codingclip.com/editor/canary/lib.min.js:241246:75)
    at injectIntl(Connect(TitledComponent))
    at ProjectFetcherComponent (https://codingclip.com/editor/canary/lib.min.js:308849:7)
    at ConnectFunction (https://codingclip.com/editor/canary/lib.min.js:241246:75)
    at injectIntl(Connect(ProjectFetcherComponent))
    at QueryParserComponent (https://codingclip.com/editor/canary/lib.min.js:309529:7)
    at ConnectFunction (https://codingclip.com/editor/canary/lib.min.js:241246:75)
    at FontLoaderComponent (https://codingclip.com/editor/canary/lib.min.js:306108:3)
    at ConnectFunction (https://codingclip.com/editor/canary/lib.min.js:241246:75)
    at ErrorBoundary (https://codingclip.com/editor/canary/lib.min.js:294601:5)
    at ConnectFunction (https://codingclip.com/editor/canary/lib.min.js:241246:75)
    at ErrorBoundaryWrapper
    at IntlProvider (https://codingclip.com/editor/canary/lib.min.js:236950:9)
    at ConnectFunction (https://codingclip.com/editor/canary/lib.min.js:241246:75)
    at LocalizationWrapper (https://codingclip.com/editor/canary/lib.min.js:308173:3)
    at ConnectFunction (https://codingclip.com/editor/canary/lib.min.js:241246:75)
    at HashParserComponent (https://codingclip.com/editor/canary/lib.min.js:306341:7)
    at ConnectFunction (https://codingclip.com/editor/canary/lib.min.js:241246:75)
    at IntlProvider (https://codingclip.com/editor/canary/lib.min.js:236950:9)
    at ConnectFunction (https://codingclip.com/editor/canary/lib.min.js:241246:75)
    at Provider (https://codingclip.com/editor/canary/lib.min.js:240957:20)
    at AppStateWrapper (https://codingclip.com/editor/canary/lib.min.js:301993:7)
(anonymous) @ instrument.js:109
overrideMethod @ react_devtools_backend.js:4026
./node_modules/minilog/lib/web/formatters/minilog.js.logger.write @ lib.min.js:200381
onItem @ lib.min.js:200215
emit @ lib.min.js:199792
./node_modules/minilog/lib/common/filter.js.Filter.write @ lib.min.js:200113
onItem @ lib.min.js:200215
emit @ lib.min.js:199792
./node_modules/minilog/lib/common/transform.js.Transform.write @ lib.min.js:200199
o.error @ lib.min.js:200140
componentDidCatch @ lib.min.js:294631
callback @ lib.min.js:226506
callCallback @ lib.min.js:218670
commitUpdateQueue @ lib.min.js:218691
commitLifeCycles @ lib.min.js:227056
commitLayoutEffects @ lib.min.js:229773
callCallback @ lib.min.js:210297
sentryWrapped @ helpers.js:74
invokeGuardedCallbackDev @ lib.min.js:210346
invokeGuardedCallback @ lib.min.js:210408
commitRootImpl @ lib.min.js:229498
unstable_runWithPriority @ lib.min.js:267475
runWithPriority$1 @ lib.min.js:217628
commitRoot @ lib.min.js:229337
performSyncWorkOnRoot @ lib.min.js:228676
(anonymous) @ lib.min.js:217679
unstable_runWithPriority @ lib.min.js:267475
runWithPriority$1 @ lib.min.js:217628
flushSyncCallbackQueueImpl @ lib.min.js:217674
flushSyncCallbackQueue @ lib.min.js:217661
discreteUpdates$1 @ lib.min.js:228767
discreteUpdates @ lib.min.js:210108
dispatchDiscreteEvent @ lib.min.js:212241
sentryWrapped @ helpers.js:74
Show 4 more frames
```

**Comment by sparrowhe** [comment]
卸载sound-editor后，事件监听并未被成功注销
